"""phase5_resume_chat

Revision ID: 24522cd05f04
Revises: 4b937c7066fe
Create Date: 2026-05-18 15:26:43.050873
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24522cd05f04'
down_revision: Union[str, None] = '4b937c7066fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_chat_messages',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_chat_messages_resume_id'), 'resume_chat_messages', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_chat_messages_user_id'), 'resume_chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_chat_messages_user_id'), table_name='resume_chat_messages')
    op.drop_index(op.f('ix_resume_chat_messages_resume_id'), table_name='resume_chat_messages')
    op.drop_table('resume_chat_messages')
    # ### end Alembic commands ###
