"""add_highlights_to_work_experience

Revision ID: 3ecc7cc049b4
Revises: 67bc59924e83
Create Date: 2026-05-24 21:23:49.610800
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3ecc7cc049b4'
down_revision: Union[str, None] = '67bc59924e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interview_sessions_resume_id_fkey', 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.add_column('resume_work_experience', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_work_experience', 'highlights')
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key('interview_sessions_resume_id_fkey', 'interview_sessions', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###
