"""phase6_generation_id

Revision ID: 67bc59924e83
Revises: 24522cd05f04
Create Date: 2026-05-19 16:25:53.838255
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67bc59924e83'
down_revision: Union[str, None] = '24522cd05f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('generation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_interview_questions_generation_id'), 'interview_questions', ['generation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_questions_generation_id'), table_name='interview_questions')
    op.drop_column('interview_questions', 'generation_id')
    # ### end Alembic commands ###
