"""add_cascade_delete_fix

Revision ID: e2cfa58e5cd2
Revises: 3ecc7cc049b4
Create Date: 2026-06-25 23:17:44.557897
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2cfa58e5cd2'
down_revision: Union[str, None] = '3ecc7cc049b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tailored_resumes_source_resume_id_fkey', 'tailored_resumes', type_='foreignkey')
    op.create_foreign_key(None, 'tailored_resumes', 'resumes', ['source_resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tailored_resumes', type_='foreignkey')
    op.create_foreign_key('tailored_resumes_source_resume_id_fkey', 'tailored_resumes', 'resumes', ['source_resume_id'], ['id'])
    # ### end Alembic commands ###
