"""phase2_jd_tailor

Revision ID: f2201d14bffa
Revises: c906dfc7ff14
Create Date: 2026-05-17 15:57:56.807547
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f2201d14bffa'
down_revision: Union[str, None] = 'c906dfc7ff14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_analysis',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('implicit_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_score', sa.Integer(), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('position_title', sa.String(length=200), nullable=True),
    sa.Column('company_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_analysis_user_id'), 'jd_analysis', ['user_id'], unique=False)
    op.create_table('tailored_resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_resume_id', sa.UUID(), nullable=False),
    sa.Column('jd_analysis_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('optimized_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tailoring_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jd_analysis_id'], ['jd_analysis.id'], ),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_user_id'), 'tailored_resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_resumes_user_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    op.drop_index(op.f('ix_jd_analysis_user_id'), table_name='jd_analysis')
    op.drop_table('jd_analysis')
    # ### end Alembic commands ###
